In [2]:
import numpy as np

myList = [1, 2, 3]
x = np.array(myList)
x

array([1, 2, 3])

In [3]:
y = np.array([[4, 5, 6, 7], [6, 7, 8, 9]])
y

array([[4, 5, 6, 7],
       [6, 7, 8, 9]])

In [4]:
y.shape

(2, 4)

In [5]:
z = np.arange(0, 30, 2)
z

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [6]:
x = x.reshape(3, 1)
x

array([[1],
       [2],
       [3]])

In [7]:
o = np.linspace(0, 2, 9)
o

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [8]:
o.resize(3, 3)
o

array([[ 0.  ,  0.25,  0.5 ],
       [ 0.75,  1.  ,  1.25],
       [ 1.5 ,  1.75,  2.  ]])

In [9]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [10]:
np.zeros((4, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [11]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [12]:
np.diag(o)

array([ 0.,  1.,  2.])

In [13]:
np.array([1, 2, 3] * 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [14]:
np.repeat([5, 4, 3], 3)

array([5, 5, 5, 4, 4, 4, 3, 3, 3])

In [15]:
np.ones([2, 3], int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
np.vstack([4*x, 3*x])

array([[ 4],
       [ 8],
       [12],
       [ 3],
       [ 6],
       [ 9]])

In [17]:
np.hstack([y*2])

array([[ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a+b

array([5, 7, 9])

In [19]:
a*b

array([ 4, 10, 18])

In [20]:
a/b

array([ 0.25,  0.4 ,  0.5 ])

In [21]:
a-b

array([-3, -3, -3])

In [22]:
a%b

array([1, 2, 3], dtype=int32)

In [23]:
a**b

array([  1,  32, 729], dtype=int32)

In [24]:
a.dot(b)

32

In [25]:
c = np.array([a, a**2])
c

array([[1, 2, 3],
       [1, 4, 9]])

In [26]:
c.T

array([[1, 1],
       [2, 4],
       [3, 9]])

In [27]:
c.dtype

dtype('int32')

In [28]:
a.sum()

6

In [29]:
a.max()

3

In [30]:
a.min()

1

In [31]:
a.mean()

2.0

In [32]:
d = np.arange(13)**2
d
# return matrix of 13 value, each value with exponent 2


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

In [33]:
str(d[0]) + ", " + str(d[3]) + ", " + str(d[0:3])

'0, 9, [0 1 4]'

In [34]:
e = np.arange(36)**2
e.resize(6, 6)
e

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]], dtype=int32)

In [35]:
e[1:4, 2:5]

array([[ 64,  81, 100],
       [196, 225, 256],
       [400, 441, 484]], dtype=int32)

In [36]:
e[e > 256]

array([ 289,  324,  361,  400,  441,  484,  529,  576,  625,  676,  729,
        784,  841,  900,  961, 1024, 1089, 1156, 1225], dtype=int32)

In [37]:
test = np.random.randint(0, 10, [4, 3])
test

array([[2, 1, 7],
       [3, 3, 7],
       [1, 4, 2],
       [4, 2, 3]])

In [40]:
for i, row in enumerate(test):
    print("row", i, "is", row)

row 0 is [2 1 7]
row 1 is [3 3 7]
row 2 is [1 4 2]
row 3 is [4 2 3]


In [41]:
test2 = test**2
test2

array([[ 4,  1, 49],
       [ 9,  9, 49],
       [ 1, 16,  4],
       [16,  4,  9]], dtype=int32)

In [42]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[2 1 7] + [ 4  1 49] = [ 6  2 56]
[3 3 7] + [ 9  9 49] = [12 12 56]
[1 4 2] + [ 1 16  4] = [ 2 20  6]
[4 2 3] + [16  4  9] = [20  6 12]


In [43]:
n_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
n_array.ravel()
# ravel() method flattens array


array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
n_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
n_array.ndim
# returns number of dimension of array


2